name: pantrymob
description: Pantry mobile is the mobile app for the Pantry system
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image:
  dio:
  font_awesome_flutter:
  google_maps_flutter:
  get:
  http:
  intl:
  intro_slider:
  path_provider:
  shared_preferences:
  shimmer: 
  spider_chart:
  webview_flutter:
  get_it:
  queries:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
flutter:
  uses-material-design: true
  fonts:
    - family: Cabin
      fonts:
        - asset: fonts/Cabin-Regular.ttf
  assets:
    - assets/
    - assets/jsons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon-pantry.png"    
